# Generated by Django 4.1 on 2022-10-05 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untirta', '0003_fakultas_alter_dosen_fakultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='Fakultas',
        ),
        migrations.DeleteModel(
            name='Fakultas',
        ),
        migrations.AddField(
            model_name='dosen',
            name='kelompok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='untirta.kelompok'),
        ),
    ]
