# Generated by Django 4.1 on 2022-10-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untirta', '0004_kelompok_remove_dosen_fakultas_delete_fakultas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='kelompok',
            new_name='Fakultas',
        ),
    ]
