# Generated by Django 4.1 on 2022-10-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('untirta', '0005_rename_kelompok_dosen_fakultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fakultas', models.IntegerField(max_length=50)),
                ('nama_fakultas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prodi', models.IntegerField(max_length=50)),
                ('nama_prodi', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='Fakultas',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='Prodi',
        ),
        migrations.DeleteModel(
            name='Kelompok',
        ),
        migrations.AddField(
            model_name='dosen',
            name='id_fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='untirta.fakultas'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='id_prodi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='untirta.prodi'),
        ),
    ]
